version: "3.7"
services:
  database:
    image: postgres
    container_name: "cloud_storage_database"
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTRGRES_DATABASE: postgres
    #volumes:
    #    - ./pgdata:/var/lib/postgresql/data

  app:
    image: cloud_storage:latest
    container_name: "cloud_storage"
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update